### PR TITLE
App Initialization GUI

### PR DESCRIPTION
**Pull request by jwildfire**
# Overview

Adds a GUI that allows users to select charts and load domain-level data before initializing the full safetyGraphics app. For now, the functionality is deployed in a new `safetyGraphicsInit()` function and looks like this:

sgloader

Think this is ready for review, but there are a few features to add later including: 
- Adding a "Load Charts" button that allows users dynamically add charts from other packages/folders
- Currently the data load module resets whenever charts change. Would be nice to maintain data sets once they are loaded. 
- Not currently passing the order of charts to the app - should be really easy to fix. 
- Would be nice to let the users copy/save the code for a standalone `safetyGraphicsApp()` call. 
- Would also be nice to add some unit tests. 

# Test Notes

Run `safetyGraphicsInit()` and play with the workflow. Button should be disabled if not all domains are loaded.

### CODE REVIEW

**Review by xni7 — APPROVED** [review]
Looks amazing! it works well just couple of minor observations

- {sortable} is a new dependency not found, perhaps need to put in the DESCRIPTION Imports?
- Does it still require attaching {safetyCharts} pkg first? no item called "package:safetyCharts" on the search list?
- in `tests/testthat/module_examples/loadCharts/app.R` ex1_data() is not found.

**Comment by jwildfire** [comment]
> * {sortable} is a new dependency not found, perhaps need to put in the DESCRIPTION Imports?

yep - I added it in a later commit 

> * Does it still require attaching {safetyCharts} pkg first? no item called "package:safetyCharts" on the search list?

It does, but I filed #559 to deal with this, so going to ignore it here. 

> * in `tests/testthat/module_examples/loadCharts/app.R` ex1_data() is not found.

Removed this file for now. We can add tests later if desired.

**Comment by xni7** [comment]
Not able to upload .sas7bdat files " Ooops Something went wrong..." csv uploads fine.  I also tried datamods directly and got the same results. Are you able to load sas data?

**Comment by jwildfire** [comment]
> Not able to upload .sas7bdat files " Ooops Something went wrong..." csv uploads fine. I also tried datamods directly and got the same results. Are you able to load sas data?

Hmm, [their docs](https://github.com/dreamRs/datamods/#import) say sas is supported, but I haven't tried it honestly. Will play around and see if there's a setting we need to tweak next week.

**Comment by jwildfire** [comment]
@xni7 I was getting the same error, and put in a quick fix in `datamods`, but now can't recreate. Can you confirm that you are still getting the issue after updating all dependencies? If so, can you try again after `devtools::install_github("jwildfire/datamods")` and confirm that it fixes things? 

If that works for you, I'll file an issue/PR to {datamods}.

**Comment by jwildfire** [comment]
Going to go ahead and merge this since the issues seems to be with a dependency. Will file a few related issues for future work.

**Comment by xni7** [comment]
> @xni7 I was getting the same error, and put in a quick fix in `datamods`, but now can't recreate. Can you confirm that you are still getting the issue after updating all dependencies? If so, can you try again after `devtools::install_github("jwildfire/datamods")` and confirm that it fixes things?
> 
> If that works for you, I'll file an issue/PR to {datamods}.

Updated all the pkgs, it still does not load SAS for me... when I installed your github fork it stopped working with csv as well. The following error msg was observed on the console

`Warning in rep(yes, length.out = len) :
  'x' is NULL so the result will be NULL`

**Pull request merged**
