### PR TITLE
Mapping refactor

### LINKED ISSUE #560: Show Mapping Side-by-side with data preview
Would be nice to see the data preview while mapping ...

### PR DESCRIPTION
**Pull request by jwildfire**
# Overview

Updated the mapping page so that the user has the option to view a data set preview while completing the mapping process as shown below. 

image

Fixes #560 #579.

# Test Notes

Play with the new mapping page and make sure nothing major is broken.

### CODE REVIEW

**Comment by xni7** [comment]
Very nice feature! only comment is it does not show side by side 
image

**Comment by jwildfire** [comment]
Can you try again now, @xni7? 

I was having trouble getting `fluidRow()` to behave, so I just did the layout in css. I just going to move to fixed width for now, so the data/chart should be side-by-side if window is at least 1000px wide. I'll also file an issue to make it reactive for someone who is better with css or shiny layouts (looking at @samussiah or @MayaGans ...).

**Comment by xni7** [comment]
fe5ef9e works! DT table a little narrow, but should be ok.
image

**Comment by jwildfire** [comment]
@xni7 Made a few more formatting tweaks, and think it's looking good now. Want to give it one more quick review on your end before I merge?

**Comment by xni7** [comment]
Yes it looks great now!

**Pull request merged**
