### PR TITLE
Add htmlwidget init functions

### LINKED ISSUE #465: safetyOutlierExplorer and safetyResultsOverTime widgets initialization
@jwildfire , I tried an ADaM dataset with AVISIT and AVISITN columns, but couldn't render safetyOutlierExplorer or safetyResultsOverTime widgets. ` The value "VISIT" for the this.config.x.column setting does not match any column in the provided dataset.`

After referring to their JS Data Guidelines, two widgets requires other metadata/mapping than `visit_col` and `visitn_col`. 

- [outlier widget: `time_cols`](https://github.com/RhoInc/safety-outlier-explorer/wiki/Data-Guidelines#data-specification)
- [boxplot widget: `time_settings`](https://github.com/RhoInc/safety-results-over-time/wiki/Data-Guidelines)

Two considerations

- Add a test for ADaM data with `AVISIT` and `AVISITN` only, e.g. [tests/testthat/module_examples/chartsRenderWidget/app.R](https://github.com/SafetyGraphics/safetyGraphics/blob/dev/tests/testthat/module_examples/chartsRenderWidget/app.R). I added a safetyOutlierExplorer widget and additional mapping and got it rendered.

```r
mappingLabs$time_cols <- data.frame(
  value_col = c("AVISIT", "ADY"),
  type = c("ordinal", "linear"),
  order_col = c("AVISITN" , "null"),
  rotate_tick_labels = c(T,F),
  vertical_space = c(100,0)
)
```
-  Add widget init function in config/workflow. The [Chart Config Vignette](https://github.com/SafetyGraphics/safetyGraphics/wiki/Chart-Configuration-Vignette-(v2)#example-3---htmlwidgets-and-init-functions) is really helpful! I followed the [aeExplorer_init()](https://github.com/SafetyGraphics/safetyCharts/blob/dev/inst/config/workflow/aeExplorer_init.R) example and created a custom workflow for safetyOutlierExplorer_init() function and added to its YAML. It worked like a charm!

```r
safetyOutlierExplorer_init<- function(data, settings){
    print(data)
    print(settings)
    
    settings$time_cols <- data_frame(
        value_col = c(settings[["visit_col"]], settings[["studyday_col"]]),
        type = c("ordinal", "linear"),
        order_col = c(settings[["visitn_col"]] , "null"),
        rotate_tick_labels = c(T,F),
        vertical_space = c(100,0)
    )
    
    return(list(data=data,settings=settings))
}
```

Comments

- I think the widget initialization is "hidden" in the code backend, and users need to familiar with the JavaScript Data Specifications. It will be challenging for non technical users. 
- Some of the widget JS settings are not in the meta data, perhaps consider some chart specific control UIs using Shiny on those charts?

### PR DESCRIPTION
**Pull request by jwildfire**
@xni7 Updated the metadata as discussed in #465.  Let me know if the widgets render out of the box with the update. 

fix #465.

### CODE REVIEW

**Review by xni7 — COMMENTED** [review]
@jwildfire , changing the meta data AVISIT and AVISITN does not seem to be sufficient. For example, safetyOutlierExplorer widget cannot render in the following function call, even if the `visit_col` and `visitn_col` are correctly mapped to `AVISIT` and `AVISITN`. 

```r
safetyGraphicsApp(  
  domainData=list(
    labs=safetyGraphics::labs %>%  select(-VISIT, -VISITNUM), 
    aes=safetyGraphics::aes, 
    dm=safetyGraphics::dm
  ),
  meta = safetyGraphics::meta, 
  charts=NULL,
  mapping=NULL,
  chartSettingsPaths = NULL)
```

The issue is safetyOutlierExplorer htmlwidget is expecting a list of `time_cols` in the settings, which is not found in the current meta data. The workaround is to use the init() function in YAML workflow. Not sure if `time_cols` is general enough to add to the global meta data, or we could create a safetyOutlierExplorer shiny module wrapper and add it there?

```r
safetyOutlierExplorer_init<- function(data, settings){
    print(data)
    print(settings)
    
    settings$time_cols <- data_frame(
        value_col = c(settings[["visit_col"]], settings[["studyday_col"]]),
        type = c("ordinal", "linear"),
        order_col = c(settings[["visitn_col"]] , "null"),
        rotate_tick_labels = c(T,F),
        vertical_space = c(100,0)
    )
    
    return(list(data=data,settings=settings))
}
```

**Comment by jwildfire** [comment]
Hmm, I think it makes sense that it's breaking. Hardcoding [here](https://github.com/SafetyGraphics/safetyGraphics/blob/165651d98c6894646f84884d1c9f7a24336d25f7/R/chartRenderer.R#L53-L96) was making this work in v1.0.

Still a bit confused why this is rendering in the default build. At any rate, I'll clean this up and ping you for review.

**Comment by jwildfire** [comment]
Ok, figured out why default renderer works. `VISIT` and `VISITNUM` are the defaults expected in javascript, so we just got lucky. As you explained above, visit_col is just being ignored and needs to be added via an init function. Will set that up in safetyCharts now. 

```
        time_cols: [
            {
                type: 'ordinal',
                value_col: 'VISIT',
                label: 'Visit',
                order_col: 'VISITNUM',
                order: null,
                rotate_tick_labels: true,
                vertical_space: 100
            },
```

**Comment by jwildfire** [comment]
OK - I think this is fixed - for real now. Try running with this branch and safetycharts@outlierinit

**Review by xni7 — APPROVED** [review]
Looks good, in reference to https://github.com/SafetyGraphics/safetyCharts/pull/41

**Pull request merged**
