### PR TITLE
Updates for Easier Connect Deployments

### PR DESCRIPTION
**Pull request by elimillera**
Hey @jwildfire,

Curious about what you think about this. I added in some golem functions and that made the deployment really easy. It also has the benefit of allowing for easy deployments to shiny-server and shinyapps.io.

I'm getting a note about excessive packages so I would understand if this isn't the way we would want to do it. If that is the case, I'll do some digging and remove the golem dependancies.

### CODE REVIEW

**Comment by jwildfire** [comment]
Thanks for putting this together, @elimillera! I'm assuming you deploy by pointing `rsconnect::deployApp` at `app.R`?

I was actually planning to push to CRAN and release this morning, so I might hold off and add this as a v2.0.1 or 2.1.

**Comment by jwildfire** [comment]
Looks like that note is going to pop up if we add any new packages. Seems like they flag >20 dependencies (and we are at 20). Going to file a few issues for removing some of the packages that are lightly used.

**Comment by elimillera** [comment]
@jwildfire Exactly. I included the files here that golem generates for rsconnect deployments so you can either use `rsconnect::deploy` or the blue publish button in RStudio. I'll look to work around without using `golem` to get rid of this issue. No need to hold up the CRAN deployment.

**Comment by jwildfire** [comment]
Sounds great! 

Since this is a fairly technical improvement, I wonder if we could use `golem` as an optional dependency via `suggests()` and then build in a little bit of conditional logic with `isLoadedNamespace('golem')`?

**Comment by jwildfire** [comment]
Fixes #626.

**Comment by jwildfire** [comment]
Thanks @elimillera. `writeManifest()` seemed to help! Though I didn't change the manifest after generating it, so 🤷. App is live [here](https://jwildfire.shinyapps.io/safetyGraphics/), but doesn't seem like css came though? Any thoughts there? Maybe easier to debug on a quick call next week?

**Comment by jwildfire** [comment]
Just took another shot and managed to break the page (again)! I'll send you a meeting invite for next week and maybe we can debug with screenshare.

**Comment by jwildfire** [comment]
Got it all working after fixing up #651. Moved `app.R` from the root dir to `/inst/deploy`

Default demo [here](https://jwildfire.shinyapps.io/safetyGraphics/) and also got a customized version using the QT demo running [here](https://jwildfire.shinyapps.io/QTDemo/) 

Merging now - thanks again for setting this up @elimillera.

**Review by jwildfire — APPROVED** [review]

**Pull request merged**
